version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@database:3306/ms_lucienne?schema=public
      RABBITMQ_URL: amqp://rabbitmq:5672
      NODE_ENV: development
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_lucienne
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3.11.0-rc.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
