version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@database:3306/ms_lucienne?schema=public
      NODE_ENV: development
  database:
    image: mariadb:10.9.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_lucienne
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
