name: Master CD

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn test:cov
      - run: yarn test:cov:integration
  cd:
    name: CD Pipeline
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(node -p -e "require('./package.json').version")

      - name: Build Docker Image
        run: docker build -t \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }}

      - name: Push Latest Image to Docker Hub
        run: docker tag \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest && \
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
